### PR TITLE
Fix function args

### PR DESCRIPTION
**Pull request by getong**
The library does not compile under erlang/otp 21.

### CODE REVIEW

**Comment by getong** [comment]
@tsloughter 
This build fail at erlang 21 is the rebar3 version is too old, it is 3.4.7
see the erlang/rebar3#1778 
But I checkout the https://github.com/travis-ci/travis-cookbooks/blob/master/cookbooks/travis_build_environment/attributes/default.rb#L106
The rebar3 are downloaded from https://s3.amazonaws.com/rebar3/rebar3
And I download the rebar3 from the url, the rebar3 version is 3.6.1
The rebar3 is needed to be updated.

**Comment by getong** [comment]
It seems to be the travis-ci/travis-cookbooks wrong, it get the rebar3 for a long time, and not update.
see the travis-ci/travis-cookbooks#990

**Comment by getong** [comment]
@fishcakez  @tsloughter 
It finally works, and a new tag is needed for otp 21.

**Comment by getong** [comment]
@fishcakez @tsloughter 
The pr is mainly fix this problem:
```
rebar3 compile
===> Verifying dependencies...
===> Compiling acceptor_pool
===> Compiling src/acceptor.erl failed
src/acceptor.erl:162: function handle_init/6 undefined
src/acceptor.erl:165: function handle_init/6 undefined

src/acceptor.erl:221: Warning: function handle_init/7 is unused
src/acceptor.erl:234: Warning: function handle_init/1 is unused

```
I am using otp 21.

**Comment by fishcakez** [comment]
Thanks @getong, looks like two PRs landing at some time did not conflict at git level but did in the code.

**Comment by getong** [comment]
@fishcakez 
would you push a new tag to hex.pm?

**Comment by tsloughter** [comment]
May as well wait until my PR is in and he can cut 1.0.0.

**Pull request merged**
