### PR TITLE
close the socket at the terminate function

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by getong** [comment]
If we close the LSocket at the terminate function, the test code will also be rewriten.
@fishcakez If you think this pr is worth, I will change the test code. If not, close this pr.

**Comment by fishcakez** [comment]
We should close the listen socket now that the pool owns the socket that the child processes can monitor the socket and exit.

**Comment by tsloughter** [comment]
Ah damn, I thought we already closed the listen socket on terminate.

I'll make a patch to do that and that will make this PR obsolete, correct? @fishcakez @getong

**Comment by tsloughter** [comment]
So I went to implement this and realized that this PR is exactly what I thought needed to be implemented...

Is this code not closing the listen sockets?

**Comment by getong** [comment]
The code was quite a long time, I am not sure.

**Pull request closed without merging**
